FROM node:8

# Create app directory
WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y \
  uuid-dev \
  libevent-dev

COPY . .

RUN npm run prestart

COPY node_modules/agora-node-rtm/libagora_rtm_sdk.so /usr/lib/

EXPOSE 8080

CMD [ "node", "./dist/index.js" ]